### ISSUE TITLE
[Frontend]: Add pool name to the pool details in the cards and the details popup

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/hype#127]

**Comment by farebord** [comment]
@VargaElod23 Could you elaborate on the description for this one? Adds a few screenshots or add a link to the detail into figma?

**Comment by farebord** [comment]
@VargaElod23 Is it just adding the poolname to the cards and details popup??

**Comment by Elod23** [comment]
Yep

**Comment by Malak67** [comment]
@farebord The missing property is the `projectName` .The logic is there you basically just need to import it along with the other properties from the .effects.tsx files, and then display it in the UI.
Files where you need to do this are:
CardDetails.tsx
Card.tsx

Should be really easy. Ping me if you have any issues.
