### ISSUE TITLE
[Chore]: Add unit tests to components

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/hype#128]
Add unit tests to following components:
- [x] background
- [x] button
- [ ] card
- [ ] connect-wallet-btn
- [ ] header
- [x] input
- [ ] modals
- [x] not-available
- [x] textarea
- [ ] tooltip
- [ ] transaction

**Comment by farebord** [comment]
Some components have been tested. Others will be testes once we have a Wagmi mock done.
