### ISSUE TITLE
[Backend & Smart Contracts]: Create proposal for CR-database use

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/hype#143]
- [x] Brainstorm and create proposal for IPFS use in the backend & FE for metadata.
- [x] Estuary reach-out happened.

**Comment by VargaElod23** [comment]
Reached out to [Estuary](https://docs.estuary.tech/) who are a public solution provider that give us both the data storage of IPFS and the benefits of Filecoin.

**Comment by VargaElod23** [comment]
The guys from Estuary got back to me real quick. Here are the credentials to be used:
Username: `taraxa`
PW: `TaraxaOps2022`
Login at https://estuary.tech/home

**Comment by Malak67** [comment]
All solutions are described here:
https://docs.google.com/document/d/10k6aBC3Qn8gDQV4eNrjGgALskM3hedO1BEonbH4qViA/edit

We decided on the last one with The Graph!
