### ISSUE TITLE
[Backend] Calculate weekly bonus

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/hype#262]
Need a cron that adds a reward each week for the top user in the leaderboard.
This is per Hype Pool.

ATM we're just gonna give out 2K TARA for our pools.

Need to add a separate endpoint for cron jobs as we don't want them to run on all backend instances.

**Comment by Malak67** [comment]
Leaderboard rewards, we reward the top 3 leaders from each week, #1 gets 10k, #2 gets 5k, #3 gets 2.5k; Eventually this should be a part of the Pool Definition defined during the creation process. For now let's just code it in.
