### ISSUE TITLE
Frontend: Fix small visual bugs in the app

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/hype#43]
- [x] Search icon is out of the searchbox in the homepage.
- [x] Sidebar is not containing the full infinite scroll background darkening.
- [x] Sidebar is causing width overflow(scrollbar).
- [x] Sidebar has the wrong z-index(needs the highest).
- [x] Match fonts from design properly(Inter everywhere): add it to the central theme.
- [x] Fix card title(1rem).
- [x] Move card detail popup trigger only to the See Details button.
- [x] Homepage body padding should be a bit bigger and responsive based on view width (use theme breakpoints). Set max-width of inner body matching the designs. See: https://www.figma.com/file/9EzCXQAVV6bVuKAaZnB0pp/Social-Listening-App-v0.1?node-id=213%3A4093 
- [x] Introduce `react-player` for video on homescreen: https://www.npmjs.com/package/react-player .
- [x] Change homescreeen background color to #F7F7F7, add it to theme.
- [x] When on Add Hype Pool page or Redeem page, header shows active link but after refresh it shows the default link as active, and not the current page

**Comment by Malak67** [comment]
@farebord The search icon is fixed in my branch so you can ignore that one.

**Comment by Malak67** [comment]
> Hey @VargaElod23 could you clarify this one? Move card detail popup trigger only to the See Details button.

Hi @farebord! I think I can explain this one. We noticed that when you click on any hype card, it triggers the modal. But we want the modal to be triggered only when we click on the 'Details' button, not anywhere on the card. Does that make sense?

**Comment by farebord** [comment]
@Malak67 @VargaElod23 

![Image](https://user-images.githubusercontent.com/602693/174811746-d2eff90d-f24c-4ac6-8d36-e35a6f3c3748.png)

This sizing seems inconsistent with the width breakpoints. On Figma its 1316px, and 1200 will be the close breakpoint to that, but that breakpoint will break the card structure as shown in the next image:

![Image](https://user-images.githubusercontent.com/602693/174812036-7d6737b3-0a62-457d-82f6-7658316144f8.png)
