### ISSUE TITLE
Frontend Bug - Joined pools on Profile page (mobile)

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/hype#89]
The hype pools don't look great in the Joined pools section of the Profile page (text overlap, button too big).

![Joined pools](https://user-images.githubusercontent.com/3051409/176920796-fb8453e1-cff2-40cd-8b84-3ac4d2328848.png)

**Comment by farebord** [comment]
![Image](https://user-images.githubusercontent.com/602693/177406613-755950a1-41ac-4482-902a-a0e0b96f3144.png)

This is already fixed in dev.
